### ISSUE TITLE
 `decode_jpeg`  causes issue with standing-laying classifier

### ISSUE THREAD

**Issue by prajurock** [Welthungerhilfe/cgm-rg#170]
`img = tf.image.decode_jpeg(img, channels=3)`
Standing-laying classier perform wrong due to problem with the above line

https://github.com/Welthungerhilfe/cgm-rg/blob/fa41f5089211ebd3c00d0ad96682d956a464d323/src/utils/preprocessing.py#L122

**Comment by 4bhishek10** [comment]
Hey I am new to this and want to contribute to open source can you please guide me

**Comment by prajurock** [comment]
> Hey I am new to this and want to contribute to open source can you please guide me

Do you have experience with TensorFlow and Python?

**Comment by prajurock** [comment]
Do you understand the code which i linked?
